name = "NLS_Fit"
uuid = "3b0ca1fe-482a-4a6a-9bcb-ed831cc48d07"
authors = ["Vincent Picaud"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
NLS_Solver = "4f18ef6b-35d7-46eb-a297-26b97f1ff488"

[compat]
julia = "1.6"
